### ISSUE TITLE
김수현 진행상황

### ISSUE THREAD

**Issue by pcppang** [pcppang/ScitStudy#10]
# 1월 둘째주 목표

## 공통 

- [ ] 스프링 2장 완료
- [x] 뉴스 기사

## 개인 

- [ ] Spring Boot 책 Thymeleaf 부분부터 시작하기  
- [ ] 수학강좌 듣기

**Comment by suleit** [comment]
## 1. 치현이 기사

### 본문 
> コンビニなどで銀行口座の開設ができる最新のATMをセーブん銀行が今年の秋から導入することがわかりました。
現在、銀行口座の開設には本人確認のため店舗に行くか、身分証のコピーを送る必要があります。
関係者によりますと、セブン銀行が導入するATMは最新の顔認証技術によって、免許証などの顔写真を読み取ったうえでATMの前に立って、顔を撮影すると、本人確認が数秒で完了するということです。
セブン銀行は今年の秋から新型ATMを切り替えをすめ、他のインターネット銀行や地方銀行の口座開設手続きも代行する予定です。

* 単語
1. 口座の開設　こうざのかいせつ　구좌의 개설
2. 顔認証技術　かおにんしょうきじゅつ 얼굴인식기술
2. 数秒　すうびょう 수초
2. 切り替え　きりかえ 바꿔침
2. 手続き　てつづき 수속
2. 代行　だいこう 대행 

## 2. 명환이 기사

### 본문
> 너무길어서 생략 

* 単語
1. 丁重 ていちょう　정중한
1. 扱い あつかい　접대, 취급
1. 生み出す　うみだす　창출하다, 낳다.
1. 備わる そなわる　갖춰지다, 구비되다, 비치되다 
1. ぞんざい　겉날림, 조악한 
1. 比較　ひかく　비교
1. 際立つ　きわだつ　뛰어나다, 두드러지다, 눈에 보이다.
1. コンセンサス 합의 
1. 至る　いたる　도달하다.
1. 極端 きょくたん　극단 
1. 競合　きょうごう　경합 
1. 降す　くだす　내리다. 하달하다 (下す　降す의 차이?)
1. 膨大 ぼうだい　막대한
1. 費やす　ついやす　쓰다, 소비하다, 허비하다, 낭비되다
1. 長時間　ちょうじかん　장시간 
1. 数多く　かずおおく　많이, 여러번 
1. 独断　どくだん　독단
1. 基づく　もとづく　기반한
1. 溢れる　あふれる　넘치다
1. 頼る　たよる　의지하다 믿다.
1. 下請け　したうけ　하청 
1. 孫会社　まごかいしゃ　자회사의 자회사 
1. 劣悪　れつあく 열악 
1. 低賃金　ていちんぎん　저임금
1. 原石　げんせき　원석

**Comment by suleit** [comment]
Spring Boot 책 Thymeleaf 부분부터 시작하기
 수학강좌 듣기
 스프링 2장 완료
--> 다음주로 이월 처리 

*현진행 스프링 1.6까지

**Comment by suleit** [comment]
진도 너무 많이 밀렸음
틈틈이 공부하는 습관 위해 노력할 것
술먹어도 매일분량 빼먹지말고 할것
수면시간 줄여야 할듯
