### ISSUE TITLE
김수현 뉴스기사

### ISSUE THREAD

**Issue by pcppang** [pcppang/ScitStudy#12]
# 1월 둘째주 뉴스기사 발표

+ 기사 제목 : 
+ 기사 원문 Url :

**Comment by suleit** [comment]
「Googleアシスタント」に通訳モードが登場、スマートディスプレイで提供へ

기사주소
https://headlines.yahoo.co.jp/hl?a=20190109-35131002-cnetj-sci

요약본 및 의견 ㅡ목요일까지

**Comment by suleit** [comment]
추가 참고 기사  2019年「Googleアシスタント」の11個の最新トピックス #CES2019
https://robotstart.info/2019/01/09/google-assistant-at-ces-2019.html

**Comment by suleit** [comment]
##単語
ゆくゆく 장래는, 가는 도중, 가면서 
通訳 （つうやく）　통역
繰り返す　되돌려준다.
~における　~의 경우의, ~의 
模索する (もさく）모색하다
最適な （さいてき）최적의  
音声認識機能　（おんせいにんしききのう）음성인식기능
遠からぬ　（とおからぬ）멀지 않은 
セクレタリー 　비서 
組み込む （くみこむ）짜 넣다. 편입하다.
