### ISSUE TITLE
여명환 진행상황

### ISSUE THREAD

**Issue by pcppang** [pcppang/ScitStudy#8]
# 1월 둘째주 목표

## 공통 

- [ ] 스프링 2장 완료
- [ ] 뉴스 기사

## With 치현
- [ ] 어른들을 위한 수학 4장 완료
- [ ] 안드로이드 프로토타입 개발 완료

## 개인 
- [ ] 일본인과의 통화
- [ ] CS : OS 강의 완료

**Comment by YeoMyeongHwan** [comment]
### 2019년 1월 7일 월요일
**일본어 기사 선정**
**스프링 Git 연동**
**스프링 (p~104)**

**Comment by YeoMyeongHwan** [comment]
### 2019년 1월 7일 월요일
_일본어 기사선정_
**스프링 Git 연동**
**스프링 (p~104)**

**Comment by YeoMyeongHwan** [comment]
### 2019년 1월 7일 월요일

- **일본어 기사 선정**
- **스프링 Git 연동**
- **스프링 (p~104)**

**Comment by YeoMyeongHwan** [comment]
### 2019년 1월 8일 화요일

- 스프링 DB(MariaDB) 연동 개헤멤

**Comment by YeoMyeongHwan** [comment]
****2019년 1월 9일 수요일

- **일본어 기사 완성**
- **스프링 & DB 연동 해결**
- **스프링(p~104)까지 밀린 코드 완성**
- **수학 2강까지 완강**

**Comment by YeoMyeongHwan** [comment]
### 2019년 1월 10일 목요일

- 치현이형 일본어 기사 읽기
- 스프링 1장(p ~143) 완료
- 수학 3.4 까지 수강
